### ISSUE TITLE
Schema item ApplianceModel could be confusing

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilm_metadata#18]
Given that Appliances have models, and ApplianceModel  refers to the disaggregation model or method being use it might be better named DisaggregationModel or DisaggregationMethod to improve the clarity of the schema.

**Comment by JackKelly** [comment]
Excellent point. I agree. If you submit a pull request then I'll merge it.
This would be a great opportunity for you to try out the process of
submitting a pull request (after first forking and making modifications).
Github have some great guides on this (search for "github forking
repository" or similar).

**Comment by gjwo** [comment]
I am in the middle of generating my household metadata, and I have found some more additions, so I will have a go when I have finished

**Comment by JackKelly** [comment]
Great stuff. Thank you. No rush.

**Comment by gjwo** [comment]
OK I have done that now

**Comment by JackKelly** [comment]
Thanks for this.  I'll close this issue for now.
