### ISSUE TITLE
Total Harmonic Distortion in MeterDevice

### ISSUE THREAD

**Issue by haderazzini** [nilmtk/nilm_metadata#25]
Hello

I have a site meter which generate samples of the Total Harmonic Distortion every second. I'd like to add it to the data set but the list of physical_quantity in MeterDevice has only {‘power’, ‘energy’, ‘cumulative energy’, ‘voltage’, ‘current’, ‘frequency’, ‘power factor’, ‘state’, ‘phase angle’}.

How I should deal with it?

Regards,

Hader

**Comment by JackKelly** [comment]
Great question!

We need a new `physical_quantity` identifier to represented THD.  Do you think `THD` is what we should use?  Or perhaps we should go with the longer - but self-documenting - `total harmonic distortion`

**Comment by haderazzini** [comment]
I believe ` total harmonic distortion` is better because follows the same pattern in the list.

Could you add `temperature ` too? One of my smart plug samples temperature too. It is designed to work together air conditioners.

**Comment by JackKelly** [comment]
Good idea.  Done.
